<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Barman.Application\Barman.Application.csproj" />
    <ProjectReference Include="..\Barman.Domain\Barman.Domain.csproj" />
  </ItemGroup>

</Project>
